I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID b8c9818c-37da-4949-9cf5-f098dd646ff1;
	- _myState = 8192;
	- _name = "Boat";
	- _modifiedTimeWeak = 3.6.2017::15:35:32;
	- _lastID = 1;
	- weakCGTime = 3.6.2017::15:35:32;
	- strongCGTime = 3.6.2017::15:35:18;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID d3d7f978-c929-4955-a5d1-ac234bf92c03;
			- _myState = 8192;
			- _name = "length";
			- _modifiedTimeWeak = 3.6.2017::15:35:25;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

