I-Logix-RPY-Archive version 8.13.0 Java 9802402
{ IClass 
	- _id = GUID e0a9e74c-a9f2-46fa-aa46-63a393ea42cc;
	- _myState = 8192;
	- _name = "Bus";
	- _modifiedTimeWeak = 1.25.2017::16:6:24;
	- _lastID = 1;
	- weakCGTime = 1.25.2017::16:6:24;
	- strongCGTime = 1.25.2017::16:5:48;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID 09f862c7-88b4-4b9f-b228-e79a0e696788;
			- _myState = 8192;
			- _name = "maximumNumberOfPassengers";
			- _modifiedTimeWeak = 1.25.2017::16:6:14;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

