I-Logix-RPY-Archive version 8.13.0 Java 9802402
{ IClass 
	- _id = GUID 2dd60d5e-5cc3-4337-b05a-c40f51bf806f;
	- _myState = 8192;
	- _name = "Car";
	- _modifiedTimeWeak = 1.22.2017::16:0:49;
	- _lastID = 1;
	- weakCGTime = 1.22.2017::16:0:49;
	- strongCGTime = 1.22.2017::16:0:26;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID a3c8196d-ce32-4b8f-a7ca-9a0b3210dab5;
			- _myState = 8192;
			- _name = "numberOfWheels";
			- _modifiedTimeWeak = 1.22.2017::16:0:35;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

