I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID 6d343515-1abc-44dd-a3c4-9a9777ea8937;
	- _myState = 8192;
	- _name = "Helicopter";
	- _modifiedTimeWeak = 2.27.2017::15:45:19;
	- _lastID = 1;
	- weakCGTime = 2.27.2017::15:45:19;
	- strongCGTime = 2.27.2017::15:45:2;
	- Operations = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IPrimitiveOperation 
			- _id = GUID 75e8cf88-d016-487a-9fdb-52727ee3077e;
			- _myState = 10240;
			- _name = "Operation_0";
			- _modifiedTimeWeak = 2.27.2017::15:45:19;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "void";
				- _id = GUID 38d26ae8-de64-4b2e-8b3e-d6cbe8e0a76d;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

