I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID 67d9aa39-3bb3-489f-9abb-0755806eca78;
	- _myState = 8192;
	- _name = "Jeep";
	- _modifiedTimeWeak = 2.15.2017::18:4:31;
	- _lastID = 1;
	- weakCGTime = 2.15.2017::18:4:31;
	- strongCGTime = 2.15.2017::18:4:18;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID 443be9e0-e58a-4ebd-b90d-27e67d25762c;
			- _myState = 10240;
			- _name = "attribute_0";
			- _modifiedTimeWeak = 2.15.2017::18:4:31;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

