I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID c0e9e4b3-c9a7-470d-8426-73cc26f371a3;
	- _myState = 8192;
	- _name = "Plane";
	- _modifiedTimeWeak = 3.1.2017::16:56:13;
	- _lastID = 1;
	- weakCGTime = 3.1.2017::16:56:13;
	- strongCGTime = 3.1.2017::16:56:3;
	- Operations = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IPrimitiveOperation 
			- _id = GUID 02ce7434-008c-4460-a281-3b6481475c1f;
			- _myState = 10240;
			- _name = "Operation_0";
			- _modifiedTimeWeak = 3.1.2017::16:56:6;
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "void";
				- _id = GUID 38d26ae8-de64-4b2e-8b3e-d6cbe8e0a76d;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

