I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID c959ad7f-f7f3-4164-882a-14baa9dda5b3;
	- _myState = 8192;
	- _name = "Train";
	- _modifiedTimeWeak = 3.5.2017::15:48:42;
	- _lastID = 1;
	- weakCGTime = 3.5.2017::15:48:42;
	- strongCGTime = 3.5.2017::15:48:27;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID 6d6cdd65-b9d8-4944-9ce8-7d3fb39e90a7;
			- _myState = 8192;
			- _name = "numberOfCars";
			- _modifiedTimeWeak = 3.5.2017::15:48:42;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

