I-Logix-RPY-Archive version 8.14.0 Java 9810022
{ IClass 
	- _id = GUID 1a6d1027-7fe7-4e91-b4f4-8bcc4ac7199a;
	- _myState = 8192;
	- _name = "Truck";
	- _modifiedTimeWeak = 2.15.2017::17:35:6;
	- _lastID = 1;
	- weakCGTime = 2.15.2017::17:35:6;
	- strongCGTime = 2.14.2017::17:48:33;
	- Attrs = { IRPYRawContainer 
		- size = 1;
		- value = 
		{ IAttribute 
			- _id = GUID 51dc684a-af6e-4856-8040-8e4563cba9aa;
			- _myState = 10240;
			- _name = "attribute_0";
			- _modifiedTimeWeak = 2.14.2017::17:48:39;
			- _typeOf = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypesJava.sbs";
				- _subsystem = "PredefinedTypesJava";
				- _class = "";
				- _name = "int";
				- _id = GUID 3b5a0555-e8e5-4b86-9ea1-95ae819b6564;
			}
			- _isOrdered = 0;
			- _protection = iPublic;
			- _static = 0;
			- _isReference = 0;
			- _isConstant = 0;
		}
	}
	- _multiplicity = "";
	- _itsStateChart = { IHandle 
		- _m2Class = "";
	}
	- _classModifier = Unspecified;
}

